spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # Es para que espere que JPA cree las tablas antes de ejecutar los scripts
                                          # que están dentro de los archivos .sql

  #Si hay un data.sql no hace falta colocar las siguientes propiedades sql referidas a dicho archivo pero si hay un
  #data.sql y colocamos las primera propiedad (data-locations) referida a otro archivo . sql, no toma en cuenta el
  #archivo data.sql (no lo ejecuta)  sino que ejecuta el otro .sql. Si queremos que se ejecuten ambos debemos
  # colocar esta propiedad para ambos archivos.
  sql:
    init:
      data-locations:
        - classpath:data.sql
      #mode: always   #Propiedad necesaria para MySql pero no para H2.

  h2:
    console:
      enabled: true
